name: "Publish"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Publish"
        run: ./script/publish
        env:
          DOCKERHUB_USERNAME: "chrisgavin"
          DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
